##### Load the package "DIHC_FeatureManager" which is in the same directory as this notebook (or your main python script/notebook)

In [9]:
# Importing necessary modules
import pandas as pd
import numpy as np
from DIHC_FeatureManager.DIHC_FeatureManager import *

##### Reading sample data from the file "signal_data.csv" which is in the same directory as this notebook (or your main python script/notebook)

In [10]:
print(f'Data reading started...')
samp_df = pd.read_csv('./signal_data.csv')
samp_df

Data reading started...

           signal  label
0      -17.777778      0
1        0.195360      0
2        0.195360      0
3        0.586081      0
4        0.195360      0
...           ...    ...
921595 -33.797314      0
921596 -27.545788      0
921597 -17.777778      0
921598  -8.791209      0
921599  -4.884005      0

[921600 rows x 2 columns]

##### Observing the shape and columns of the data

In [11]:
print(f'Data reading completed...')
samp_df.shape, samp_df.columns

Data reading completed...

((921600, 2), Index(['signal', 'label'], dtype='object'))

##### This data file contains 3 columns: "time", "signal", and "label". We will use only the "signal" column for feature extraction
##### For simplicity only the first 20 seconds of the signal is used for feature extraction

In [12]:
print(f'Data minimization started...')
# sig_freq = 1 #256
# samp_data = np.array([52, 54, 6, 45, 14, 40, 42, 48, 52, 20, 28, 8, 63, 47, 23])

sig_freq = 256
# samp_data = samp_df['signal'].values.tolist()
samp_data = samp_df.loc[:20*sig_freq-1, 'signal'].values#.tolist()
# samp_data = samp_df.loc[:5100, 'signal'].values#.tolist()
# samp_data = samp_df.iloc[:20*256-1, 0:1].values#.tolist()
# print(len(samp_data))
# print(samp_data.shape, samp_data)
print(f'Data minimization completed...')
print(samp_data.shape)
samp_data

Data minimization started...
Data minimization completed...
(5120,)

array([-17.77777778,   0.19536019,   0.19536019, ...,  -0.58608059,
         0.19536019,  -0.19536019])


##### Create the object of the class "DIHC_FeatureManager" and call the method "get_segments_for_data" to extract features from the data
##### Use different parameters of the method "get_segments_for_data" to extract different number of segments

In [13]:
print(f'Data segmentation started...')
feat_manager = DIHC_FeatureManager()
seg_arr = feat_manager.get_segments_for_data(samp_data, segment_length=5, signal_frequency=sig_freq)
print(f'Data segmentation completed...')

Data segmentation started...
Segment started...
Generating segment# 1
Generating segment# 2
Generating segment# 3
Generating segment# 4
Segment finished...
Data segmentation completed...

##### Display the segmented data

In [14]:
print(seg_arr.shape)
seg_arr

(4, 1280)

array([[-17.77777778,   0.19536019,   0.19536019, ..., -15.82417582,
        -15.43345543, -18.94993895],
       [-21.68498168, -18.94993895, -16.21489621, ...,  29.89010989,
         42.002442  ,  50.5982906 ],
       [ 59.97557998,  67.78998779,  74.43223443, ...,   0.58608059,
          3.32112332,   4.88400488],
       [  4.49328449,   2.93040293,   4.88400488, ...,  -0.58608059,
          0.19536019,  -0.19536019]])

##### Create the object of the class "DIHC_FeatureManager" and call the method "extract_features_from_data" to extract features from the data
##### Use different parameters of the method "extract_features_from_data" to extract different features

In [15]:
print(f'Feature extraction started...')
feat_manager = DIHC_FeatureManager()
# feat_df = feat_manager.extract_features_from_data(samp_data, segment_length=5, signal_frequency=sig_freq)
feat_df = feat_manager.extract_features_from_data(samp_data, segment_length=5, signal_frequency=sig_freq, has_matlab_engine=False)
# feat_df = feat_manager.extract_features_from_data(samp_data, feature_names=[DIHC_FeatureGroup.fdNlPw, DIHC_FeatureGroup.fdNlPwBnd], segment_length=5, signal_frequency=sig_freq, has_matlab_engine=False)
# feat_df = feat_manager.extract_features_from_data(samp_data, feature_names=[DIHC_FeatureGroup.tdNlEn, DIHC_FeatureGroup.td], segment_length=5, signal_frequency=sig_freq, has_matlab_engine=True)
# feat_df = feat_manager.extract_features_from_data(samp_data, feature_names=[DIHC_FeatureGroup.tdNlEn, DIHC_FeatureGroup.tdNl], segment_length=5, signal_frequency=sig_freq, has_matlab_engine=True)
print(f'Feature extraction completed...')

Feature extraction started...
Data started segmenting...[]
Segment started...
Generating segment# 1
SEG data [-17.77777778   0.19536019   0.19536019 ... -15.82417582 -15.43345543
 -18.94993895]
Extracting all features.

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished

Generating segment# 2
SEG data [-21.68498168 -18.94993895 -16.21489621 ...  29.89010989  42.002442
  50.5982906 ]
Extracting all features.

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished

Generating segment# 3
SEG data [59.97557998 67.78998779 74.43223443 ...  0.58608059  3.32112332
  4.88400488]
Extracting all features.

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished

Generating segment# 4
SEG data [ 4.49328449  2.93040293  4.88400488 ... -0.58608059  0.19536019
 -0.19536019]
Extracting all features.
Segment finished...
Finished generating features for all segments...
Feature extraction completed...

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished

##### Display the extracted features

In [16]:
print(feat_df.shape)
feat_df

(4, 81)

,maximum,minimum,mean,median,standardDeviation,variance,kurtosis,skewness,numberOfZeroCrossing,positiveToNegativeSampleRatio,...,fd_variance_other,fd_kurtosis_other,fd_skewness_other,spectralEntropy,fd_bandPower,fd_bandPower_alpha,fd_bandPower_beta,fd_bandPower_delta,fd_bandPower_theta,fd_bandPower_other
0,67.79,-88.11,0.44,0.20,27.23,741.72,0.14,-0.33,86.0,1.04,...,626712.01,-0.65,0.54,3.59,763.30,279.87,17.84,387.91,72.32,6.15
1,92.01,-81.86,2.73,2.74,26.46,700.24,0.18,0.02,77.0,1.16,...,448145.09,-0.30,0.33,3.69,7.30,150.74,16.46,394.10,91.81,7.30
2,96.70,-133.43,-3.39,-2.54,35.90,1288.69,0.90,-0.08,82.0,0.89,...,1327713.58,-0.52,0.03,3.57,5.78,334.15,26.78,731.33,158.03,5.78
3,62.32,-66.62,2.58,2.93,23.42,548.52,0.20,-0.23,107.0,1.35,...,713879.74,0.26,0.84,3.80,6.88,160.07,19.87,287.11,64.72,6.88